In [1]:
import pandas as pd
import glob

In [2]:
files = glob.glob(r"../데이터/전처리데이터/*preprocessed*.csv")
files

['../데이터/전처리데이터\\preprocessed_coupangeats_reviews_playstore.csv',
 '../데이터/전처리데이터\\preprocessed_yogiyo_reviews_playstore.csv',
 '../데이터/전처리데이터\\preprocessed_ddangyo_reviews_playstore.csv',
 '../데이터/전처리데이터\\preprocessed_baemin_reviews_playstore.csv']

In [3]:
dfs = [pd.read_csv(f, encoding="utf-8-sig") for f in files]
df_all = pd.concat(dfs, ignore_index=True)
len(df_all)

24019

In [4]:
df_all.columns

Index(['app', 'platform', 'reviewId', 'userName', 'content', 'score',
       'thumbsUpCount', 'at', 'filtered_keywords', 'sentiment_label',
       'sentiment'],
      dtype='object')

In [5]:
df_all.head()

,app,platform,reviewId,userName,content,score,thumbsUpCount,at,filtered_keywords,sentiment_label,sentiment
0,쿠팡이츠,playstore,b5c90090-0583-4082-9897-2d64b366ca25,씨지뷔,배민보다좋은 써비쓰~,5,0,2025-12-15 10:19:50,"['써비', '쓰다']",1.0,positive
1,쿠팡이츠,playstore,095f0bf5-0ee7-4692-95c5-cfcfcd866433,Ruth도리,사용하기 편리해서 쿠팡이츠만 사용하게 되요.,4,0,2025-12-15 07:44:15,['편리하다'],1.0,positive
2,쿠팡이츠,playstore,e4b41922-ed1c-40b7-8c99-25e959383476,이수,다 좋은데요... 기존 도착예정시간보다 한참 늘려놓고 예정시간보다 일찍 도착했다고 ...,4,0,2025-12-15 01:45:13,"['일찍', '같다', '도착', '기존', '동네', '알림', '한참', '없애...",1.0,positive
3,쿠팡이츠,playstore,fadff53f-e01b-4687-bd62-ab5b09671953,박귀지,좋은 어플입니다 쿠팡와우는 정말 기가 막히게 잘 만든거 같습니다ㅋㅋ,5,0,2025-12-15 01:32:35,"['정말', '같다', '막히다', '만들다']",1.0,positive
4,쿠팡이츠,playstore,17fb7288-9a9a-4bda-9ba7-267f16a6a9c4,또아아빠,쿠팡털렸지만 못끊것네 편해서..,5,0,2025-12-15 00:37:23,"['털리다', '끊다', '편하다']",1.0,positive

In [6]:
df_all['filtered_keywords'] = df_all['filtered_keywords'].apply(lambda x : x.translate(str.maketrans("","","[],'")).split())
df_all.head()

,app,platform,reviewId,userName,content,score,thumbsUpCount,at,filtered_keywords,sentiment_label,sentiment
0,쿠팡이츠,playstore,b5c90090-0583-4082-9897-2d64b366ca25,씨지뷔,배민보다좋은 써비쓰~,5,0,2025-12-15 10:19:50,"[써비, 쓰다]",1.0,positive
1,쿠팡이츠,playstore,095f0bf5-0ee7-4692-95c5-cfcfcd866433,Ruth도리,사용하기 편리해서 쿠팡이츠만 사용하게 되요.,4,0,2025-12-15 07:44:15,[편리하다],1.0,positive
2,쿠팡이츠,playstore,e4b41922-ed1c-40b7-8c99-25e959383476,이수,다 좋은데요... 기존 도착예정시간보다 한참 늘려놓고 예정시간보다 일찍 도착했다고 ...,4,0,2025-12-15 01:45:13,"[일찍, 같다, 도착, 기존, 동네, 알림, 한참, 없애다, 늘리다, 정시]",1.0,positive
3,쿠팡이츠,playstore,fadff53f-e01b-4687-bd62-ab5b09671953,박귀지,좋은 어플입니다 쿠팡와우는 정말 기가 막히게 잘 만든거 같습니다ㅋㅋ,5,0,2025-12-15 01:32:35,"[정말, 같다, 막히다, 만들다]",1.0,positive
4,쿠팡이츠,playstore,17fb7288-9a9a-4bda-9ba7-267f16a6a9c4,또아아빠,쿠팡털렸지만 못끊것네 편해서..,5,0,2025-12-15 00:37:23,"[털리다, 끊다, 편하다]",1.0,positive

In [7]:
df_all['filtered_keywords'][0][0]

'써비'

In [8]:
df_all.to_csv("../데이터/merged_reviews_playstore.csv", index=False, encoding="utf-8-sig")